# Session 07 (18 May 2018)
## PDAP-2018

### Contents

This session covered the following parts of the course [Scipy Lecture Notes](https://www.scipy-lectures.org/):

- [The NumPy array object](https://www.scipy-lectures.org/intro/numpy/array_object.html)
- [Numerical operations on arrays](https://www.scipy-lectures.org/intro/numpy/operations.html)

### Transcript

Now following is the original transcript as used in class on 18 May 2018.

In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [3]:
l = range(1000)
%timeit [i**2 for i in l]

432 µs ± 5.57 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
a = np.arange(1000)
%timeit a**2

2.05 µs ± 29.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
a = np.array([0, 1, 2, 3])

In [8]:
a.ndim

1

In [9]:
a.shape

(4,)

In [10]:
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
b.shape

(2, 3)

In [13]:
b.ndim

2

In [14]:
c = np.array([[[0, 1, 2], [3, 4, 5]]])
c

array([[[0, 1, 2],
        [3, 4, 5]]])

In [15]:
c.ndim

3

In [16]:
c.shape

(1, 2, 3)

In [17]:
len(c)

1

In [18]:
c.size

6

In [19]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(1, 4, .5)  # specify increment

array([1. , 1.5, 2. , 2.5, 3. , 3.5])

In [23]:
np.linspace(1.0, 3.5, 6)  # specify number of elements

array([1. , 1.5, 2. , 2.5, 3. , 3.5])

In [24]:
np.linspace(1.0, 3.5, 6, endpoint=False)

array([1.        , 1.41666667, 1.83333333, 2.25      , 2.66666667,
       3.08333333])

In [26]:
a = np.ones((3, 4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
c = np.eye(4)
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
d = np.diag([1, 3, 2, 4])
d

array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])

In [35]:
a = np.random.rand(4, 2)
a

array([[0.46771736, 0.48884135],
       [0.11904879, 0.12383866],
       [0.17576974, 0.4342175 ],
       [0.07940445, 0.4761454 ]])

In [53]:
b = np.random.randn(4)
b

array([-0.52627513, -0.34812723,  0.69434731, -2.14456363])

In [70]:
np.random.seed(1234)
c = np.random.randn(4)
c

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 ])

In [71]:
np.empty(4)

array([0.47143516, 1.19097569, 1.43270697, 0.3126519 ])

In [72]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [73]:
a.dtype

dtype('int64')

In [74]:
b = np.arange(5.0, )
b

array([0., 1., 2., 3., 4.])

In [75]:
b.dtype

dtype('float64')

In [76]:
c = np.arange(5, dtype='float16')
c

array([0., 1., 2., 3., 4.], dtype=float16)

In [77]:
a

array([0, 1, 2, 3, 4])

In [78]:
b

array([0., 1., 2., 3., 4.])

In [79]:
a * b

array([ 0.,  1.,  4.,  9., 16.])

In [80]:
e = np.array([True, False, False, True])
e

array([ True, False, False,  True])

In [81]:
e.dtype

dtype('bool')

In [82]:
f = np.array([1+2j, 3+4j, 5+6j])
f

array([1.+2.j, 3.+4.j, 5.+6.j])

In [83]:
f.dtype

dtype('complex128')

In [84]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
a[0], a[4], a[3]

(0, 4, 3)

In [86]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [87]:
b = np.diag(np.arange(4))
b

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [89]:
b[1, 2]

0

In [90]:
b[1:, 2]

array([0, 2, 0])

In [91]:
# reverse rows
b[::-1]

array([[0, 0, 0, 3],
       [0, 0, 2, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0]])

In [92]:
# reverse columns
b[:,::-1]

array([[0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 2, 0, 0],
       [3, 0, 0, 0]])

In [93]:
# reverse rows and columns
b[::-1, ::-1]

array([[3, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

In [94]:
b

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [96]:
b[1] = 99

In [97]:
b

array([[ 0,  0,  0,  0],
       [99, 99, 99, 99],
       [ 0,  0,  2,  0],
       [ 0,  0,  0,  3]])

In [99]:
mylist = []
for i in range(10):
    mylist.append(3*i)
mylist

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]

In [100]:
myarr = np.empty(10)
for i in range(10):
    myarr[i] = 3*i
myarr

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [104]:
np.arange(0, 27.0000000001, 3, dtype=int)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [106]:
print(b.shape)
b

(4, 4)


array([[ 0,  0,  0,  0],
       [99, 99, 99, 99],
       [ 0,  0,  2,  0],
       [ 0,  0,  0,  3]])

In [107]:
bb = b[:, np.newaxis, :]
print(bb.shape)
bb

(4, 1, 4)


array([[[ 0,  0,  0,  0]],

       [[99, 99, 99, 99]],

       [[ 0,  0,  2,  0]],

       [[ 0,  0,  0,  3]]])

In [109]:
print(a.shape)
a

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
aa = a[np.newaxis, :, np.newaxis]
print(aa.shape)
aa

(1, 10, 1)


array([[[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]])

In [ ]:
np.expand_dims()

In [113]:
#[[4, 3, 4, 3, 4, 3],
# [2, 1, 2, 1, 2, 1],
# [4, 3, 4, 3, 4, 3],
# [2, 1, 2, 1, 2, 1]]

a = np.array([[4, 3], [2, 1]])
a

array([[4, 3],
       [2, 1]])

In [114]:
np.tile(a, (2, 3))

array([[4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1],
       [4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1]])

In [122]:
np.random.seed(3)
a = np.random.randint(0, 21, 15)
a

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6,  0, 20, 12,  7, 14])

In [123]:
a % 3 == 0

array([False,  True, False,  True, False, False, False,  True, False,
        True,  True, False,  True, False, False])

In [124]:
mask = (a % 3 == 0)
a[mask]

array([ 3,  0,  9,  6,  0, 12])

In [125]:
b = a[mask]
b

array([ 3,  0,  9,  6,  0, 12])

In [131]:
a.shape, mask.shape, a[mask].shape

((15,), (15,), (6,))

In [127]:
g = np.arange(0, 100, 10)
g

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [133]:
ix = np.array([2, 5, 3, 4, 4])
g[ix]

array([20, 50, 30, 40, 40])

In [134]:
g.shape, ix.shape, g[ix].shape

((10,), (5,), (5,))

In [138]:
g

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [137]:
ix2 = np.array([[2, 5, 3], [1, 1, 0]])
g[ix2]

array([[20, 50, 30],
       [10, 10,  0]])

In [141]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [140]:
a + 1

array([1, 2, 3, 4])

In [142]:
a * 2

array([0, 2, 4, 6])

In [143]:
2**a

array([1, 2, 4, 8])

In [144]:
c = np.ones((3, 3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [145]:
c * c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [146]:
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [147]:
b = np.array([4, 2, 2, 4])
b

array([4, 2, 2, 4])

In [148]:
a == b

array([False, False,  True, False])

In [150]:
a != b

array([ True,  True, False,  True])

In [151]:
a > b

array([False, False, False, False])

In [152]:
a < (b -2)

array([ True, False, False, False])

In [154]:
np.all(a == b)

False

In [155]:
np.array_equal(a, b)

False

In [156]:
%timeit np.all(a == b)

4.73 µs ± 104 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [157]:
%timeit np.array_equal(a, b)

6.01 µs ± 180 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [158]:
h = np.array([False, True, True])
l = np.array([True, True, False])

In [159]:
np.logical_and(h, l)

array([False,  True, False])

In [160]:
np.logical_or(h, l)

array([ True,  True,  True])

In [161]:
h * l

array([False,  True, False])

In [162]:
h + l

array([ True,  True,  True])

In [163]:
u = np.ones((2, 3))
u

array([[1., 1., 1.],
       [1., 1., 1.]])

In [164]:
u.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [165]:
t = np.arange(6)
t

array([0, 1, 2, 3, 4, 5])

In [166]:
t.reshape((2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [167]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7])

In [168]:
a + b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [177]:
a

array([1, 2, 3, 4])

In [175]:
bb = b[:, np.newaxis]
print(bb.shape)
bb

(3, 1)


array([[5],
       [6],
       [7]])

In [176]:
a + bb

array([[ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11]])

In [178]:
x = np.arange(4)
y = x[:, np.newaxis]

In [179]:
x

array([0, 1, 2, 3])

In [180]:
y

array([[0],
       [1],
       [2],
       [3]])

In [182]:
x - y

array([[ 0,  1,  2,  3],
       [-1,  0,  1,  2],
       [-2, -1,  0,  1],
       [-3, -2, -1,  0]])

In [187]:
x = np.array([1, 2, 3])
y = np.arange(6).reshape((2, 3))
z = np.arange(9).reshape((3, 3))

In [188]:
x, y, z

(array([1, 2, 3]), array([[0, 1, 2],
        [3, 4, 5]]), array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]))

In [186]:
x + y

array([[1, 3, 5],
       [4, 6, 8]])

In [189]:
x + z

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [190]:
y + z

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 